f = open("haqiqiy_sonlar", 'r')
s = f.read()
f.close()
a = s.split()
k1 = list(map(lambda x: x * x, list(map(int, a))))
print(k1)
f1=open("haqiqiy_sonlar", 'w')
f1.write(" ".join(list(map(str,k1))))
f1.close()